
UNSET(IRRLICHT_INCLUDE_DIR CACHE)
FIND_PATH(IRRLICHT_INCLUDE_DIR irrlicht/irrlicht.h 
    HINTS /usr/include /usr/local/include $ENV{IRRLICHT_ROOT}/include
)

UNSET(IRRLICHT_LIB CACHE)
FIND_LIBRARY(IRRLICHT_LIB Irrlicht
	HINTS /usr/lib /usr/local/lib $ENV{IRRLICHT_ROOT}/lib
)

IF(NOT IRRLICHT_INCLUDE_DIR OR NOT IRRLICHT_LIB)
    message(SEND_ERROR "Irrlicht could not be found")
ELSE(NOT IRRLICHT_INCLUDE_DIR OR NOT IRRLICHT_LIB)
    message(STATUS "Irrlicht found: ${IRRLICHT_INCLUDE_DIR} ${IRRLICHT_LIB}")
ENDIF(NOT IRRLICHT_INCLUDE_DIR OR NOT IRRLICHT_LIB)

