
UNSET(GIT_EXECUTABLE CACHE)
FIND_PROGRAM(GIT_EXECUTABLE git
    HINTS /usr/bin /usr/local/bin $ENV{GIT_ROOT}/bin
  )
IF(GIT_EXECUTABLE)
  EXECUTE_PROCESS(COMMAND git rev-parse --short HEAD
      OUTPUT_VARIABLE _GIT_REVISION
    )
  STRING(REGEX REPLACE  "[ \t\r\n]+" "" GIT_REVISION "${_GIT_REVISION}")
ELSE(GIT_EXECUTABLE)
  SET(GIT_REVISION "default")
ENDIF(GIT_EXECUTABLE)

SET(BUILD_VERSION_MAJOR "0")
SET(BUILD_VERSION_MINOR "1")
SET(BUILD_VERSION_REVISION "${GIT_REVISION}")

